run_eth_goerli:
	set -o allexport; source .env.goerli; set +o allexport; ts-node run_eth.ts

run_ae_uat:
	set -o allexport; source .env.goerli; ts-node run_ae.ts

run_eth_development:
	set -o allexport; source .env; set +o allexport; ts-node run_eth.ts
