run_eth_goerli:
	set -o allexport; source .env.goerli; set +o allexport; ts-node run_eth.ts

run_ae_goerli:
	set -o allexport; source .env.goerli; ts-node run_ae.ts

run_eth_development:
	set -o allexport; source .env; set +o allexport; ts-node run_eth.ts

run_eth_arbitrum_goerli:
	set -o allexport; source .env.arbitrum-goerli; set +o allexport; ts-node run_eth.ts

run_ae_arbitrum_goerli:
	set -o allexport; source .env.arbitrum-goerli; ts-node run_ae.ts

run_eth_arbitrum:
	set -o allexport; source .env.arbitrum; set +o allexport; ts-node run_eth.ts

run_ae_arbitrum:
	set -o allexport; source .env.arbitrum; ts-node run_ae.ts
